export const appointments = [
    {
        "patient": {
            "id": 120728,
            "firstname": "Quinton",
            "middlename": "",
            "lastname": "Apple",
            "nickname": "",
            "name": "Quinton  Apple",
            "gender": "Male",
            "homephone": "",
            "homephonemessage": "No Messages",
            "workphone": "",
            "workphonemessage": "No Messages",
            "mobilephone": "801-556-0056",
            "mobilephonemessage": "Text Messages",
            "otherphone": "",
            "otherphonemessage": "No Messages",
            "preferredphone": "homephone",
            "email": "dgreene53@gmail.com",
            "provider_id": null,
            "comments": "",
            "clinician_id": 277,
            "welcome_email_sent": null,
            "address1": "5676 S 900 E",
            "address2": "",
            "city": "Sandy",
            "state": "Utah",
            "zipcode": "84094",
            "date_of_birth": "1966-05-13",
            "marital_status": "",
            "language": "",
            "race": "",
            "education": "",
            "grade": "",
            "employment": "",
            "hipaa_agreement": false,
            "pcp_release": "not_set",
            "status": true,
            "created_at": "2020-02-11T14:40:26.242-07:00",
            "updated_at": "2022-04-11T17:48:39.532-06:00",
            "credits": 0,
            "stripe_customer_id": null,
            "patient_balance": 135,
            "insurance_balance": 2389,
            "practice_id": 241,
            "self_pay_billing_company_id": 1519,
            "active_providers_count": 1,
            "mobile_carrier": "Verizon Wireless",
            "patient_number": "402770180",
            "justification_assessment": null,
            "primary_diagnosis_code_id": 192135,
            "secondary_diagnosis_code_id": 191997,
            "currency": "usd",
            "primary_diagnosis_code_iv_id": null,
            "ssn": "",
            "payor": "EMI Health",
            "cc": false,
            "reminder_active": true,
            "reminder_email": "dgreene53@gmail.com",
            "authorizations": [
                {
                    "id": 4914,
                    "allowed_number": "5",
                    "allowed_start_date": null,
                    "authorization_code": "234f2r2f",
                    "authorization_code_start_date": "2021-06-01",
                    "authorization_code_end_date": "2021-07-31",
                    "created_at": "2021-08-13T17:59:56.351-06:00",
                    "updated_at": "2021-08-13T18:01:03.108-06:00",
                    "remaining": 0,
                    "patient_provider_id": 70196,
                    "authorization_type": "EAP 1",
                    "comments": ""
                },
                {
                    "id": 4915,
                    "allowed_number": "5",
                    "allowed_start_date": null,
                    "authorization_code": "3t3f22",
                    "authorization_code_start_date": "2021-08-01",
                    "authorization_code_end_date": "2021-08-31",
                    "created_at": "2021-08-13T18:01:40.266-06:00",
                    "updated_at": "2021-11-12T10:32:36.167-07:00",
                    "remaining": 0,
                    "patient_provider_id": 70196,
                    "authorization_type": "EAP 2",
                    "comments": ""
                }
            ]
        },
        "id": 3203331,
        "clinician_id": 277,
        "clinician": {
            "id": 277,
            "email": "dgreene53@gmail.com",
            "created_at": "2015-04-16T13:19:26.382-06:00",
            "updated_at": "2022-04-14T02:58:26.177-06:00",
            "name": "Don Greene",
            "stripe_customer_id": "cus_J0mYSOMCPnxo40",
            "last_4_digits": "4242",
            "formal_name": "Donall Greene, LCSW",
            "mobile_phone": "801-556-0056",
            "receive_text_messages": false,
            "home_phone": null,
            "state_license_number": "53-13131313",
            "title": "LCSW",
            "clinician_type": "Therapist",
            "taxonomy_code": null,
            "supervision": false,
            "subaccount": false,
            "password_updated": true,
            "practice_id": 241,
            "time_zone": "Mountain Time (US & Canada)",
            "subscription_level": null,
            "status": true,
            "twilio_sid": null,
            "ical_token": "1f0535d9eaa4484ea6ef8560e2a6ffaf",
            "ical_names": 2,
            "clinician_dsm_version": "DSM-V",
            "firstname": "Don",
            "middlename": "",
            "lastname": "Greene",
            "delete_pending": false,
            "currency": null,
            "supervisor_id_old": null,
            "payment_status": "Paid",
            "subpractice": "",
            "supervisor_id": null,
            "income_type": "Gross Income",
            "income_rate": 10,
            "authentication_token": "3k_7y8Zx4QaT9ADt3KJy",
            "logout_timeout": 0,
            "bill_under_supervisor": false,
            "is_bie_tab_hideable": false,
            "is_telehealth_enabled": true,
            "encrypted_otp_secret": null,
            "encrypted_otp_secret_iv": "NQ7ivpggQRRQXW0F\n",
            "encrypted_otp_secret_salt": "_bQLZOVDRSVb7gfLKy9A7Qg==\n",
            "consumed_timestep": 54992992,
            "otp_required_for_login": false,
            "otp_backup_codes": null,
            "otp_secret": null
        },
        "patient_id": 120728,
        "service_code": {
            "id": 2004,
            "code": "90837"
        },
        "location": {
            "id": 4310,
            "informal_name": "Telehealth Sandy-10"
        },
        "procedure_code_modifier": {
            "id": 369,
            "code": "AJ"
        },
        "complete_code": "90837-AJ",
        "address": null,
        "duration": 60,
        "frequency": "Recurs Weekly",
        "scheduled_until": "2022-06-04T00:00:00.000-06:00",
        "memo": "",
        "email_reminder": true,
        "text_reminder": true,
        "cancelled": false,
        "missed": false,
        "created_at": "2022-04-11T17:37:18.303-06:00",
        "updated_at": "2022-04-11T17:37:18.533-06:00",
        "start_at": "2022-04-11T16:00:00.000-06:00",
        "end_at": "2022-04-11T17:00:00.000-06:00",
        "location_id": 4310,
        "practice_id": 241,
        "reminders_cache": "[{\"id\":3965113,\"description\":\"Create a \\u003cspan class='patient_link' data-action='progress_note'\\u003estandard progress\\u003c/span\\u003e or \\u003cspan class='patient_link' data-action='soap_note'\\u003esoap progress\\u003c/span\\u003e or \\u003cspan class='patient_link' data-action='process_note'\\u003eprocess note\\u003c/span\\u003e\"}]",
        "is_self_pay": false,
        "all_day": false,
        "parent_id": 3203331,
        "allow_delete": true,
        "procedure_code_modifier_id": 369,
        "sent_email_reminder": false,
        "sent_text_reminder": false,
        "sent_partner_email_reminder": false,
        "sent_partner_text_reminder": false,
        "units": 1,
        "service_code_id": 2004,
        "partner_email_reminder": true,
        "partner_text_reminder": true,
        "has_patient_group": false,
        "therapy_group_id": null,
        "has_note": false,
        "has_group_progress_notes": false,
        "invoice_submitted": false,
        "is_calendar_event": false,
        "attendances_attributes": [
            {
                "id": 1599113,
                "patient_id": 120728,
                "name": "Quinton  Apple",
                "create_invoice": true,
                "_destroy": false,
                "missed": false,
                "email_reminder": true,
                "text_reminder": true,
                "sent_email_reminder": false,
                "sent_text_reminder": false,
                "patient": {
                    "id": 120728,
                    "name": "Quinton  Apple",
                    "reminder_active": true,
                    "reminder_email": "dgreene53@gmail.com",
                    "mobilephone": "801-556-0056",
                    "mobile_carrier": "Verizon Wireless",
                    "mobilephonemessage": "Text Messages"
                }
            }
        ],
        "appointment_authorizations": [],
        "add_on_codes_attributes": [],
        "additional_procedure_code_modifiers_attributes": [],
        "original_additional_procedure_code_modifiers_attributes": []
    }
]